### ISSUE TITLE
-b option returning error on first found folder content using *

### ISSUE THREAD

**Issue by falcn12** [harisokanovic/nilrt-net-boot#1]
Trying out the shell script -b blacklist option - I am getting an error in the Find functionality.

my -b option is written:
-b etc/opt/*

Which returns the error:
find: unrecognized: ./etc/opt/repo
Busybox v1.27.2 
usage: ....explanation of using 'find' not copied for space - see image

I had also tried -b etc/opt -b etc/opt/* 

Got the same error.

![-b_BlacklistError-ShellScript](https://user-images.githubusercontent.com/26440038/73986583-d8837200-48f2-11ea-9ab1-9eef5e984cd4.jpg)

**Comment by harisokanovic** [comment]
Do you have a folder under **/etc/opt/** with a space in it's name?
Can you try quoting the -b argument -- i.e. **-b "etc/opt/*"** ?

**Comment by harisokanovic** [comment]
I added quoting for blacklist values in commit ca6e80930a. However, you should still quote all inputs that have wildcards (*). I can't prevent your shell from expanding them before nilrt-make-netboot-image.sh runs.

**Comment by falcn12** [comment]
The only two folders under etc/opt/ are
ni
repo

No spaces in the names of those folders.  Then it progresses down to the final levels where all the .ipk files are located.

**Quotes had no effect on the error.**

etc/opt/repo/ only has a linear level of directories 

etc/opt/repo/19.07/x86_64/

with no other subfolders until the x86_64 level - then:

etc/opt/repo/19.07/x86_64/base/
etc/opt/repo/19.07/x86_64/opkg-utils-0.4.1/
etc/opt/repo/19.07/x86_64/opgk-utils-0.4.1.tar.gz*
etc/opt/repo/19.07/x86_64/packages/

Under base/ is a long list of .ipk package files
Under packages/ is another long list of .ipk package files

Nothing seems to have any spaces that I can see.

**Comment by falcn12** [comment]
find . -name "* *"
found no files or folders with spaces in the names from /mnt/userfs/etc/opt on down.

**Comment by falcn12** [comment]
Downloaded the new updated shell script and ran it, it worked with - b etc/opt -b "etc/opt/*" and gave a correct output of 412MB for img.d

**Comment by harisokanovic** [comment]
Great. Linux tools are generally allergic to spaces. You get used to it after a while :)

**Comment by falcn12** [comment]
I guess one of the package names somewhere could have a space, but it didn't look like it.  Thanks for all the effort.
